# LLM 工具配置

tool:
  name: "llm_tool"
  description: "大语言模型服务工具"
  version: "1.0.0"

# 提供商配置
providers:
  openai:
    enabled: true
    api_key_env: "OPENAI_API_KEY"
    base_url: "https://api.openai.com/v1"
    models:
      default: "gpt-3.5-turbo"
      available: ["gpt-3.5-turbo", "gpt-4", "gpt-4-turbo"]
    parameters:
      temperature: 0.7
      max_tokens: 2000
      top_p: 1.0
      frequency_penalty: 0.0
      presence_penalty: 0.0
    rate_limits:
      requests_per_minute: 60
      tokens_per_minute: 90000

  anthropic:
    enabled: true
    api_key_env: "ANTHROPIC_API_KEY"
    base_url: "https://api.anthropic.com"
    models:
      default: "claude-3-haiku-20240307"
      available: ["claude-3-haiku-20240307", "claude-3-sonnet-20240229", "claude-3-opus-20240229"]
    parameters:
      temperature: 0.7
      max_tokens: 2000
      top_p: 1.0
    rate_limits:
      requests_per_minute: 50
      tokens_per_minute: 80000

  aws_bedrock:
    enabled: true
    region: "us-east-1"
    models:
      default: "anthropic.claude-3-haiku-20240307-v1:0"
      available: [
        "anthropic.claude-3-haiku-20240307-v1:0",
        "anthropic.claude-3-sonnet-20240229-v1:0",
        "anthropic.claude-3-opus-20240229-v1:0"
      ]
    parameters:
      temperature: 0.7
      max_tokens: 2000
      top_p: 1.0

# 自动选择配置
auto_selection:
  enabled: true
  strategy: "round_robin"  # round_robin, least_loaded, quality_based
  fallback_order: ["openai", "anthropic", "aws_bedrock"]
  health_check_interval: 60

# 缓存配置
cache:
  enabled: true
  ttl: 3600  # 1小时
  max_size: 1000
  key_strategy: "prompt_hash"

# 重试配置
retry:
  max_attempts: 3
  backoff_factor: 2.0
  initial_delay: 1.0
  max_delay: 30.0

# 监控配置
monitoring:
  track_usage: true
  track_latency: true
  track_errors: true
  log_requests: false  # 生产环境建议关闭